Fixing visualisation editor UI bugs
IT2901-SINTEF01/frontend pull request #105
Opened 2021-04-06 13:11 UTC by emilom

Made some changes in the visualisation editor/preview components. The mocked graph will now stay the same at each render. You can now add text to a graph without the graph looking like a dubstep track on youtube 🎉 I also made some changes in the dashboard item component. It will now cover more space and I think it looks a bit better. There was also a bug where the width of the preview stayed the same after you added text, which is now removed. Also fixed some overflow problems with tags and paragraphs. 

I don't think you storybook is the best place to review these changes, so check nellify as well :)

Close #104

2021-04-06 14:23 UTC, FredrikAugust requested changes
A few notes;)

- Entering a very long description breaks the preview
![Screenshot 2021-04-06 at 16 20 07](https://user-images.githubusercontent.com/7691547/113725788-f5345900-96f3-11eb-9ec9-9df995f4e38d.png)

- The graph re-renders every time you edit the description. When the text is pushing the left side of the graph, it will re-render a lot of times while "animating" to it's new size. I'd recommend turning on "paint on rerender" in React dev tools and using the app.

2021-04-06 14:23 UTC, FredrikAugust commented on src/components/molecules/VisualisationPreview.tsx
> +        const timeEtryMockData = mockTimeEntry(100, visualisation.axes.y.limit);
Typo. Missing `n`

2021-04-06 17:39 UTC, emilom commented
> A few notes;)
> 
> * Entering a very long description breaks the preview
>   ![Screenshot 2021-04-06 at 16 20 07](https://user-images.githubusercontent.com/7691547/113725788-f5345900-96f3-11eb-9ec9-9df995f4e38d.png)
> * The graph re-renders every time you edit the description. When the text is pushing the left side of the graph, it will re-render a lot of times while "animating" to it's new size. I'd recommend turning on "paint on rerender" in React dev tools and using the app.

Weird.. It works for me with overflow hidden. Tested with chrome and safari.

2021-04-06 21:07 UTC, FredrikAugust commented
> > A few notes;)
> > 
> > * Entering a very long description breaks the preview
> >   ![Screenshot 2021-04-06 at 16 20 07](https://user-images.githubusercontent.com/7691547/113725788-f5345900-96f3-11eb-9ec9-9df995f4e38d.png)
> > * The graph re-renders every time you edit the description. When the text is pushing the left side of the graph, it will re-render a lot of times while "animating" to it's new size. I'd recommend turning on "paint on rerender" in React dev tools and using the app.
> 
> Weird.. It works for me with overflow hidden. Tested with chrome and safari. The text should not be pushing the graph.

It was tested in Firefox on the deployed site (netlify).

2021-04-07 08:26 UTC, emilom commented
> > > A few notes;)
> > > 
> > > * Entering a very long description breaks the preview
> > >   ![Screenshot 2021-04-06 at 16 20 07](https://user-images.githubusercontent.com/7691547/113725788-f5345900-96f3-11eb-9ec9-9df995f4e38d.png)
> > > * The graph re-renders every time you edit the description. When the text is pushing the left side of the graph, it will re-render a lot of times while "animating" to it's new size. I'd recommend turning on "paint on rerender" in React dev tools and using the app.
> > 
> > 
> > Weird.. It works for me with overflow hidden. Tested with chrome and safari. The text should not be pushing the graph.
> 
> It was tested in Firefox on the deployed site (netlify).

Turns out you need
`white-space: pre-wrap;`
`word-break: break-all;`

for firefox and IE. Should be fixed now :)

2021-04-07 09:24 UTC, FredrikAugust approved these changes
Works like a charm

2021-04-07 09:25 UTC, merged