Add bar chart.
IT2901-SINTEF01/frontend pull request #156
Opened 2021-04-23 13:58 UTC by emilom

Little draft for a bar chart implementation.

This new component can be used with the same data format as linechart and thresholdchart.
It is possible to add the functionality and create a Grouped Bar where you for instance can view both tax and income from one municipality with a list of CartesianChartInput like this: 

```typescript
export type BarChartProps = {
    barNames: string[];
    yLabel?: string;
    title?: string;
    data: CartesianChartInput[];
    isPreview?: boolean;
    height: string | number;
    width: string | number;
};

const BarChart: React.FC<BarChartProps> = ({ title, yLabel, data, isPreview = false, height, width, barNames }) => {
    

    data.map((el, index) => ({
                type: 'bar',
                x: el.map((d) => d.x),
                y: el.map((d) => d.y),
                name: barNames[index],
            }))
    

    return (
        <Plot
            useResizeHandler
            data={data.map((el, index) => ({
                type: 'bar',
                x: el.map((d) => d.x),
                y: el.map((d) => d.y),
                name: barNames[index],
            }))}
            style={{ width: width, height: height, margin: '0' }}
            layout={{
                autosize: true,
                title: { text: title, x: 0, y: 0.975 },
                margin: {
                    l: 40,
                    r: 40,
                    b: 40,
                    t: 40,
                    pad: 4,
                },
                yaxis: {
                    title: yLabel,
                    automargin: true,
                },
            }}
            config={{ staticPlot: isPreview }}
        />
    );
};

export default BarChart;
```
Here’s how that would look
![image](https://user-images.githubusercontent.com/54807939/115882025-a1907200-a44c-11eb-864d-8737dc10377f.png)

2021-04-24 12:58 UTC, FredrikAugust commented on src/components/visualisations/BarChart.tsx
> +    */
Don't commit comments.

If you wish to have them in the file, and commit the rest of the file I would recommend using chunked staging (available in most GUI Git clients – [example from Tower](https://www.git-tower.com/help/guides/faq-and-tips/tips-and-tricks/chunk-line-staging/windows)).

2021-04-24 12:58 UTC, FredrikAugust commented on src/stories/BarChart.stories.tsx
> +// };
[encore](https://www.youtube.com/watch?v=yNPECkESPbU)

2021-04-24 12:58 UTC, FredrikAugust commented on src/stories/BarChart.stories.tsx
> +    data: historicAppleStockPrice.slice(Math.max(historicAppleStockPrice.length - 30, 0)),
What is the point of this? Does `historicAppleStockPrice` vary in length?

2021-04-30 09:31 UTC, FredrikAugust requested changes

2021-04-30 09:31 UTC, FredrikAugust commented on src/components/atoms/DashboardItemVariables.tsx
> +            content = '';
Implement functionality for Tax data source.

2021-04-30 09:36 UTC, FredrikAugust requested changes

2021-04-30 09:36 UTC, FredrikAugust commented on src/components/visualisations/LineChart.tsx
> +            }))}
This code is repeated between the visualisations.

2021-04-30 09:36 UTC, FredrikAugust commented on src/mockdata/mockCartesianChartInput.ts
> +    return [values.map((e, i) => ({ y: e, x: timeseries[i].toISOString() }))];
Should contain a parameter for how many series to generate.

Don't fix now as we're short on time, but keep in mind for the future.

2021-04-30 09:51 UTC, emilom commented on src/components/visualisations/LineChart.tsx
> +            }))}
added function in utils :DD

2021-05-02 12:01 UTC, FredrikAugust approved these changes

2021-05-02 12:01 UTC, merged